language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6
  - ruby-head

gemfile:
  - gemfiles/graphql_1_10.gemfile
  - gemfiles/graphql_master.gemfile


notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
